[package]
name = "beacn-mic-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
# Logging
log = "0.4.26"
simplelog = "0.12.2"

# Error Handling
anyhow = "1.0.96"

# Enum Helpers
strum = "0.27.1"
strum_macros = "0.27.1"
enum-map = "2.7.3"

# Used for SIMD EQ calculations
wide = "0.7.32"

# UI Framework
egui = "0.31.0"
egui_extras = { version = "0.31.0", features = ["svg"] }

# Ok, we need to manually deal with Window Handling
egui-winit = "0.31.0"
egui_glow = "0.31.0"
glutin = "0.32.2"

# Grab beacn-mic-lib for comms
#beacn-lib = { git = "https://github.com/beacn-on-linux/beacn-lib.git" }
beacn-lib = { path = "../beacn-lib" }

once_cell = "1.20.3"

