name: Create Release Build
on: [ workflow_dispatch, workflow_call ]
jobs:
  get_version:
    name: "Version"
    uses: ./.github/workflows/get-version.yml

  build_linux:
    name: "Create Linux Builds"
    runs-on: ubuntu-22.04
    needs: [ get_version ]
    steps:
      - name: "Check out Repository"
        uses: actions/checkout@v4

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Loading Cache"
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-release-

      - name: Install cargo-deb and cargo-generate-rpm
        run: cargo install --force cargo-deb cargo-generate-rpm

      - name: "Build Packages"
        run: ./ci/build-packages
        shell: bash

      - name: "Upload DEB Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: debian-artifact
          path: ./target/debian/*.deb

      - name: "Upload RPM Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: rpm-artifact
          path: ./target/generate-rpm/*.rpm