name: Update Generated Files

on:
  workflow_dispatch:
  push:

jobs:
  update-generated-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setting up Python
        run: |
          pip install flatpak-cargo-generator

      - name: Generate file
        run: |
          flatpak-cargo-generator Cargo.lock -o generated-sources.json

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git add generated-sources.json
            git commit -m "chore: update flatpak sources"
            git push
          fi